### ISSUE TITLE
On running `helm dependencies update` prior to building

### ISSUE THREAD

**Issue by cdancy** [wfhartford/gradle-helm#10]
Any planned support for running `helm dependencies update` prior to building the chart? If a given chart has deps things fail but if I run the proper command in the proper directory thinks work as expected.

**Comment by wfhartford** [comment]
I've pushed up a first attempt at adding this feature in the `update-dependencies` branch. That branch also includes the fix for #11. If you are so inclined, it would be great if you could give it a try and let me know if it fits your needs. At the moment, I have the new `updateDependencies{chart-name}Chart` task depended upon by the `packate{chart-name}Chart` task. I'm not sure how appropriate that is. The new task could be left to be executed manually, or let the user add a dependency to it in their build file.

I'll likely release a new beta in the next few days, but can't make any promises as I'll be travelling over the next few weeks.

**Comment by cdancy** [comment]
@wfhartford will do this morning. Stay tuned...

**Comment by cdancy** [comment]
> I'm not sure how appropriate that is.

@wfhartford yeah not sure. The `helm package` call does take an argument `-u` which will update dependencies at package time as well so that you don't need to make this additional call. From a CI/CD perspective I could see both being useful so long as they are opt-in maybe through some extension flag.

> I'll likely release a new beta in the next few days, but can't make any promises as I'll be travelling over the next few weeks.

I'm one of the maintainers of the [gradle-docker-plugin](https://github.com/bmuschko/gradle-docker-plugin) so if you need help, or looking for someone to help contribute and do releases to get the project off the ground, I can certainly do so. I haven't had a good reason to learn kotlin yet and this would force me to do so. In either event let me know.

**Comment by Blobson** [comment]
I doesn't seem that UpdateDependenciesTask made it in the master branch.
For now release 1.0.0-beta-9 is failing with:
```Error: found in requirements.yaml, but missing in charts/ directory: ...```

**Comment by wfhartford** [comment]
I've released 1.0.0-beta-10 with the chart update feature.
