### ISSUE TITLE
Download Helm always runs

### ISSUE THREAD

**Issue by jamesdbloom** [wfhartford/gradle-helm#7]
The download helm run every single build for all task.  This means that the build is completely broken on any machine without internet access.  In addition the helm file is not cached adding significant slowness to all tasks.

**Comment by wfhartford** [comment]
The download and install tasks should only run for a _clean_ build. There is no local caching other than in the build directory. You are certainly correct that this makes builds impossible on machines that are off-line. I suppose a simple way to address this would be to make the URL from which the helm distribution is downloaded configurable, so that it could be set to a URL that is accessible (either a local HTTP server, or a local file URL). I would certainly accept a pull request adding a feature like this.

I'm not sure if this work-around is possible in your situation, but it is possible to disabling the download and install tasks, and point the plugin to a local helm executable. Something like the following should do the trick:
```gradle
helm {
  install {
    executable file('/tools/helm/linux-amd64/helm')
  }
}
downloadHelm.enabled = false
installHelm.enabled = false
```

**Comment by jamesdbloom** [comment]
Yes that is helpful information about disabling the download and install tasks.
